### ISSUE TITLE
Import Array - Format for CSV

### ISSUE THREAD

**Issue by iews** [goellner/statamic-data-importer#4]
I cannot find an example for CSV array. I have delimited the file multiple ways and have had no luck in getting it to work. 

Can you provide an example CSV, Excel file, or text file that I can see the format?

**Comment by goellner** [comment]
There is a sample csv in the root of this repository: https://raw.githubusercontent.com/goellner/statamic-data-importer/master/sample-data.csv

Let me know if that helps

**Comment by iews** [comment]
Missed that file. I'll give it a go and see if I can get it right.
